### ISSUE TITLE
LTextField 在TEXT_INPUT事件中，使用text取得中文输入延迟

### ISSUE THREAD

**Issue by xiaohuidexinge** [lufylegend/lufylegend.js#75]
具体代码如下

            theTextField = new LTextField();
            theTextField.setType(LTextFieldType.INPUT);
            theTextField.x = 10;
            theTextField.y = 10;
            addChild(theTextField);

            theTextField.addEventListener(LTextEvent.TEXT_INPUT, function(e) {
            console.log("TEXT_INPUT " + theTextField.text);
            });

现象是 比如使用中文输入法输入“你”字，当“你”字输入完毕后，text取得的内容是"ni"，

**Comment by lufylegend** [comment]
LTextEvent.TEXT_INPUT获取的时机其实是LKeyboardEvent.KEY_DOWN，
你这个恐怕得在LKeyboardEvent.KEY_UP的时候才可以
你可以利用LFocusEvent.FOCUS_IN事件，通过下面代码来监听LKeyboardEvent.KEY_UP事件
    LEvent.addEventListener(LGlobal.inputTextBox, LKeyboardEvent.KEY_UP, function (e) {
        //这时LGlobal.inputTextBox.value就是你要的值
    });
