### ISSUE TITLE
LString.trim bug

### ISSUE THREAD

**Issue by yuehaowang** [lufylegend/lufylegend.js#78]
Master lufy:
I think you might forget something important. There is a slight difference between unix(OS X, Linux) and Windows on processing wraps: 
On Windows, '/r/n' indicates a wrap, while unix uses '/n' only to indicate a wrap.

So when I try process a string read from a file with wraps  with `LString.trim` on diverse OS, I got various results because of the difference I mentioned above and `LString.trim`'s bug on processing "\r". Actually, it's tough to find  their differences as character '/r' is invisible in browser's console.

That's a hidden bug.

**Comment by lufylegend** [comment]
嗯，多谢了，下个版本修正

**Comment by yuehaowang** [comment]
后来我发现这个问题并不是引擎的问题 因为我用了无数方法尝试去匹配换行符号 但是都是失败告终。由于我的字符串来自Qt读取的文件 我怀疑是Qt为统一这类差异 做了特殊处理所以用正则表达式无法匹配它们。最后我在Qt方面做了处理 就没有问题了
