### ISSUE TITLE
LLoadManage wrong progress caused by LAjax's LEvent.PROGRESS 

### ISSUE THREAD

**Issue by yuehaowang** [lufylegend/lufylegend.js#79]
Recently I might found a bug in lufylegend v1.10.1.
As the `LEvent.PROGRESS` was added in v1.10.1, the method of calculating loading progress in `LLoadManage` was changed. I found the loading progress would go wrong when I used `LLoadManage.load` to load some .mp3 files. At first, I believed that is a problem from `LLoadManage` or `LSound`, but after checking the code of the two classes carefully, I turned my attention to `LAjax`.

At the same time, I found `onProgress` callback of `LLoadManage.load(loadList, onProgress, onComplete)` will be called more times than the corresponded value, namely length of `loadList`.

I suppose this question stems from `XMLHttpRequest`'s "progress" event. As the data type is "buffer", so the "progress" event callback will be called when receiving even a few data, which causing the bug that callback of  `LLoadManage`'s LEvent.PROGRESS will be called several times.

**Comment by lufylegend** [comment]
这个bug已经发现了，只是还没有发布新版本，如果你现在需要的话，下面这个是修改方法，应该能解决你的问题
https://github.com/lufylegend/lufylegend.js/commit/459ddd6019220154e7e0e5a51d6b7abe4edb3aa2
